#include "getkey.h"
Button up;
Button down;
Button right;
Button left;
Button shift;
Button enter;
Button control;
Button tab;
Button del;
Button alt;
Button backspace;
Button esc;
Button key_q;
Button key_a;
Button key_z;
Button key_w;
Button key_s;
Button key_x;
Button key_e;
Button key_d;
Button key_c;
Button key_r;
Button key_f;
Button key_v;
Button key_t;
Button key_g;
Button key_b;
Button key_y;
Button key_h;
Button key_n;
Button key_u;
Button key_j;
Button key_m;
Button key_i;
Button key_k;
Button key_o;
Button key_l;
Button key_p;
Button one;
Button two;
Button three;
Button four;
Button five;
Button six;
Button seven;
Button eight;
Button nine;
Button zero;

void getKey(char *keyStat){
	key_q.press 	= is(keyStat[1]&0x01);
	key_a.press 	= is(keyStat[1]&0x02);
	key_z.press 	= is(keyStat[1]&0x04);
	key_w.press 	= is(keyStat[1]&0x08);
	key_s.press 	= is(keyStat[1]&0x10);
	key_x.press 	= is(keyStat[1]&0x20);
	key_e.press 	= is(keyStat[1]&0x40);
	key_d.press 	= is(keyStat[2]&0x01);
	key_c.press 	= is(keyStat[2]&0x02);
	key_r.press 	= is(keyStat[2]&0x04);
	key_f.press 	= is(keyStat[2]&0x08);
	key_v.press 	= is(keyStat[2]&0x10);
	key_t.press 	= is(keyStat[2]&0x20);
	key_g.press 	= is(keyStat[2]&0x40);
	key_b.press 	= is(keyStat[3]&0x01);
	key_y.press 	= is(keyStat[3]&0x02);
	key_h.press 	= is(keyStat[3]&0x04);
	key_n.press 	= is(keyStat[3]&0x08);
	key_u.press 	= is(keyStat[3]&0x10);
	key_j.press 	= is(keyStat[3]&0x20);
	key_m.press 	= is(keyStat[3]&0x40);
	key_i.press 	= is(keyStat[4]&0x01);
	key_k.press 	= is(keyStat[4]&0x02);
	key_o.press 	= is(keyStat[4]&0x04);
	key_l.press 	= is(keyStat[4]&0x08);
	key_p.press 	= is(keyStat[4]&0x10);
	shift.press 	= is(keyStat[4]&0x20);
	control.press 	= is(keyStat[4]&0x40);
	alt.press 	= is(keyStat[5]&0x01);
	backspace.press = is(keyStat[5]&0x02);
	tab.press 	= is(keyStat[5]&0x04);
	enter.press 	= is(keyStat[5]&0x08);
	esc.press 	= is(keyStat[5]&0x10);
	del.press 	= is(keyStat[5]&0x20);
	up.press 	= is(keyStat[5]&0x40);
	down.press 	= is(keyStat[6]&0x01);
	right.press 	= is(keyStat[6]&0x02);
	left.press 	= is(keyStat[6]&0x04);
	one.press 	= is(keyStat[6]&0x08);
	two.press 	= is(keyStat[6]&0x10);
	three.press 	= is(keyStat[6]&0x20);
	four.press 	= is(keyStat[6]&0x40);
	five.press 	= is(keyStat[7]&0x01);
	six.press 	= is(keyStat[7]&0x02);
	seven.press 	= is(keyStat[7]&0x04);
	eight.press 	= is(keyStat[7]&0x08);
	nine.press 	= is(keyStat[7]&0x10);
	zero.press 	= is(keyStat[7]&0x20);
	
	key_q.count 	+= pushCount(&key_q);
	key_a.count 	+= pushCount(&key_a);
	key_z.count 	+= pushCount(&key_z);
	key_w.count 	+= pushCount(&key_w);
	key_s.count 	+= pushCount(&key_s);
	key_x.count 	+= pushCount(&key_x);
	key_e.count 	+= pushCount(&key_e);
	key_d.count 	+= pushCount(&key_d);
	key_c.count 	+= pushCount(&key_c);
	key_r.count 	+= pushCount(&key_r);
	key_f.count 	+= pushCount(&key_f);
	key_v.count 	+= pushCount(&key_v);
	key_t.count 	+= pushCount(&key_t);
	key_g.count 	+= pushCount(&key_g);
	key_b.count 	+= pushCount(&key_b);
	key_y.count 	+= pushCount(&key_y);
	key_h.count 	+= pushCount(&key_h);
	key_n.count 	+= pushCount(&key_n);
	key_u.count 	+= pushCount(&key_u);
	key_j.count 	+= pushCount(&key_i);
	key_m.count 	+= pushCount(&key_m);
	key_i.count 	+= pushCount(&key_j);
	key_k.count 	+= pushCount(&key_k);
	key_o.count 	+= pushCount(&key_o);
	key_l.count 	+= pushCount(&key_l);
        key_p.count 	+= pushCount(&key_p);
        shift.count 	+= pushCount(&shift);
        control.count 	+= pushCount(&control);
        alt.count 	+= pushCount(&alt);
        backspace.count += pushCount(&backspace);
        tab.count 	+= pushCount(&tab);
        enter.count 	+= pushCount(&enter);
        esc.count 	+= pushCount(&esc);
        del.count 	+= pushCount(&del);
        up.count 	+= pushCount(&up);
        down.count 	+= pushCount(&down);
        right.count 	+= pushCount(&right);
        left.count 	+= pushCount(&left);
        one.count 	+= pushCount(&one);
        two.count 	+= pushCount(&two);
        three.count 	+= pushCount(&three);
        four.count 	+= pushCount(&four);
        five.count 	+= pushCount(&five);
        six.count 	+= pushCount(&six);
        seven.count 	+= pushCount(&seven);
        eight.count 	+= pushCount(&eight);
        nine.count 	+= pushCount(&nine);
        zero.count 	+= pushCount(&zero);
	
	key_q.toggle 	 = key_q.count%2;
	key_a.toggle 	 = key_a.count%2;
	key_z.toggle 	 = key_z.count%2;
	key_w.toggle 	 = key_w.count%2;
	key_s.toggle 	 = key_s.count%2;
	key_x.toggle 	 = key_x.count%2;
	key_e.toggle 	 = key_e.count%2;
	key_d.toggle 	 = key_d.count%2;
	key_c.toggle 	 = key_c.count%2;
	key_r.toggle 	 = key_r.count%2;
	key_f.toggle 	 = key_f.count%2;
	key_v.toggle 	 = key_v.count%2;
	key_t.toggle 	 = key_t.count%2;
	key_g.toggle 	 = key_g.count%2;
	key_b.toggle 	 = key_b.count%2;
	key_y.toggle 	 = key_y.count%2;
	key_h.toggle 	 = key_h.count%2;
	key_n.toggle 	 = key_n.count%2;
	key_u.toggle 	 = key_u.count%2;
	key_j.toggle 	 = key_j.count%2;
	key_m.toggle 	 = key_m.count%2;
	key_i.toggle 	 = key_i.count%2;
	key_k.toggle 	 = key_k.count%2;
	key_o.toggle 	 = key_o.count%2;
	key_l.toggle 	 = key_l.count%2;
	key_p.toggle 	 = key_p.count%2;
	shift.toggle 	 = shift.count%2;
	control.toggle 	 = control.count%2;
	alt.toggle 	 = alt.count%2;
	backspace.toggle = backspace.count%2; 
	tab.toggle 	 = tab.count%2;
	enter.toggle 	 = enter.count%2;
	esc.toggle 	 = esc.count%2;
	del.toggle 	 = del.count%2;
	up.toggle 	 = up.count%2;
	down.toggle 	 = down.count%2;
	right.toggle 	 = right.count%2;
	left.toggle 	 = left.count%2;
	one.toggle 	 = one.count%2;
	two.toggle 	 = two.count%2;
	three.toggle 	 = three.count%2;
	four.toggle 	 = four.count%2;
	five.toggle 	 = five.count%2;
	six.toggle 	 = six.count%2;
	seven.toggle 	 = seven.count%2;
	eight.toggle 	 = eight.count%2;
	nine.toggle 	 = nine.count%2;
	zero.toggle 	 = zero.count%2;
}

int is(int n){
	return !!n;
}

int pushCount(Button *any){
	if(any->press){
		if(any->flg == 0){
			any->flg = 1;
			return 1;
		}
	}else{
		any->flg = 0;
	}
	return 0;
}
